### ISSUE TITLE
Missing property "details-level"

### ISSUE THREAD

**Issue by urskog84** [tkoopman/psCheckPoint#28]
Hi tkoopman, many of the show commands in the API have the ability to get a more detail view on a object. ex. [show-hosts](https://sc1.checkpoint.com/documents/latest/APIs/index.html#introduction~v1.1). if you set the "detail-level" to "full" when you POST to fetch the Objects. you will get more info like. ipaddress, color, nat-settings, and tag...

Please add "detail-level" Property to at least the Get-CheckPointHosts

**Comment by tkoopman** [comment]
Hi. Firstly thank you for your feedback. I have planned to add this but it probably won't be until I refactor psCheckPoint code to use Checkpoint.NET project which does have the feature already. 

Workaround: While this may not be ideal you can currently do `Get-CheckPointHosts | Get-CheckPointFullObject`. This will get the result I think you are after but in the background does each as separate calls.

**Comment by tkoopman** [comment]
v1.0.0-beta1 just released which included this new functionality if you will like to test you can install the beta using "Install-Module -Name psCheckPoint -AllowPrerelease"

**Comment by tkoopman** [comment]
v1.0.0 now released.
