### ISSUE TITLE
Session log in error

### ISSUE THREAD

**Issue by jrremillard** [tkoopman/psCheckPoint#31]
Hi,
I wanted to know if this module worked with version R77.30? I am getting a certificate error and if i pass the certificate check i get Open-CheckPointSession : Unexpected character encountered while parsing value: <. Path '', line 0, position 0. at line 1 charactor 1

Any help would be great

Thank you

**Comment by tkoopman** [comment]
The Check Point management API which is what is used by psCheckPoint is only available from R80 and up. Only management needs to be R80+ as that is what psCheckPoint talks to. Your gateways can still be a lower version that is supported by R80.

Regards
Tim
