### ISSUE TITLE
Cannot use different certificate validation methods under .NET 4.5.

### ISSUE THREAD

**Issue by vturqut** [tkoopman/psCheckPoint#32]
Hi,
I'have updated my CheckPoint Module to last version (1.0.0).
When I use **-Certificatevalidation "None"** attribute, I faced error which is
 _"Open-CheckPointSession : Cannot use different certificate validation methods under .NET 4.5."_
I'm sure that my .NET version is 4.7.1

**Comment by tkoopman** [comment]
This is not the .NET version you have installed but the .NET version the standard Windows PowerShell uses. You cannot change this, as it is tied to the PowerShell version. I don't think Windows have any versions currently using higher, so only option is PowerShell Core if you need multiple authentication methods per session.

As for this error you are getting, does it happen if you open a brand new PowerShell console and run the Open-CheckPointSession command? or does it happen when you trying to connect to a second session or run other commands first?

It would be expected that once you run the command for the first time for that mgmt server you will have to use the same options when connecting again. If you need to change validation methods you need to open a new PowerShell window.

Please let me know if this helped or if it is actually happening when run on a new PowerShell window.
